class('Divider').extends(playdate.graphics.sprite)

function Divider:init(y)
	Divider.super.init(self)
print("divvv")
	local dividerImage = playdate.graphics.image.new(400, 3)
	playdate.graphics.pushContext(dividerImage)
			local lineImage = playdate.graphics.image.new(400, 3)
			playdate.graphics.pushContext(lineImage)
					playdate.graphics.setColor(playdate.graphics.kColorWhite)
					playdate.graphics.setLineWidth(1)
					playdate.graphics.drawLine(0, 1, 400, 1) 
			playdate.graphics.popContext()
			lineImage:drawFaded(0, 0, 0.35, playdate.graphics.image.kDitherTypeVerticalLine)
	playdate.graphics.popContext()
	self:setImage(dividerImage)
	self:moveTo(200, y)
	self:add()
end
